:Author: Alexie Papanicolaou
:Email: alexie@butterflybase.org
:Date: 25 November 2013

= Just_Annotate_My_proteins (JAMp) =

== Introduction == 
Whether working on a model species for biomedical, economical or evolutionary research, next-generation sequencing has enabled biologists to rapidly generate a reference sequence for downstream applications and hypotheses generation. With the exception of a limited number of species, functional annotation is conducted by _in-silico_ experiments based on sequence similarity. JAMp is a platform that allows biologists to reclaim the analysis of transcript reconstruction experiments by providing an automated, user-friendly overview of these _in-silico_ experiments.

== How does it look? == 
A core element of JAMp is its rich Graphical User Interface (GUI). Such interfaces are important not only because they allow biologists to explore their data without using the command line and spreadsheets but because it provide a vastly more efficient human-machine interface (i.e. yes, many expert bioinformaticians also use GUIs to conduct analyses!). See http://annotation.insectacentral.org/demo[this demo].

== How does it work == 
Like most bioinformatic software, JAMp and its dependencies must first be installed before end-users can use it. The process is by itself simple but Linux system administration is often an onerous task so feel free to ask our mailto:jamps-users@lists.sourceforge.net[user mailing list] if you require help.

* First, administrators install the software, including the annotation database and a website that drives the GUI. This needs to occur only once and they are very simple
** Administrators also have to install the HHblits software that we use for conducting the Hidden Markov searches. As a High Performance Computing (HPC) environment is required, your HPC administrators might be able to help (no compilation is required so that too ought to be simple - and we may be able to help)
* Second, for every reference sequence (e.g. a Trinity RNA-Seq transcript assembly), users with some command of the Linux command line) conduct the _in-silico_ experiment (currently HHblits is supported). A perl script then stores the output and relevant metadata (e.g. name of species) into the JAMp database
* The users (and the anyone with access to the website, such as paper reviewers and readers) use their browser to explore the functional annotations using a powerful yet intuitive GUI.

Too easy!

== Controlled Vocabularies == 
We use a number of control vocabularies (and ontologies) to organize the way we present functional annotation knowledge. There is no limit to what kind of vocabularies JAMp can support but we are currently using the http://www.geneontology.org[Gene Ontology]. http://www.chem.qmul.ac.uk/iubmb/enzyme/‎[Enzyme Classification] (currently primarily for bacteria), http://eggnog.embl.de[EggNOG] and http:www.genome.jp/kegg/‎[Kyoto Encyclopedia of Genes and Genomes] (KEGG).

WARNING: Users must understand a bit about the process of electronic inference. We have an unknown protein and we wish to infer what it may do. We don't have any functional data so we look for (using a software, i.e. ''in-silico''), a 'similar' known protein that has experimental evidence. We then infer that our protein has the same function. JAMP ensures that only known proteins with real experimental evidence are used in this inference, in other words, we are being careful not to do a double inference: assigning a function to our unknown protein because it is similar to another protein that has no experimental data but is similar to one that does. In theory this reduces the sensitivity of our search but the way we populate the database and identify our similar known proteins is not by BLAST but by a Hidden Markov search which is far more sensitive (see below).

== High-Performance Computing == 
IMPORTANT: Overall, annotating with JAMp is significantly faster than annotating with the traditional BLASTx approach. This is especially true in the NGS era. In the past, transcriptomic projects were composed of a few hundred reliable genes and therefore tasks based on BLAST (e.g. BLAST2GO), were commonplace. In the RNAseq era, it is commonplace that dozens of thousands of high quality transcripts are reconstructed. Further, full genome sequencing (and gene model reconstruction) is now available for hundrends of species. Further, the so called non-model species are often significantly divergent from Arabidopsis, Fruitfly, Human/Mouse, Yeast etc that a model-based, recursive yet time-consuming searches are required (such PSI-BLAST or an HMM search). 

How dow we address this problem? First, JAMp uses http://www.nature.com/nmeth/journal/v9/n2/full/nmeth.1818.html[HHblits], a HM model-based search software that searches your protein against Uniprot, builds an alignment and a model and then searches again. Importantly, thanks to the http://pubshare.genzentrum.lmu.de/scientific_computing/software/ffindex/[ffindex] software, we offer an MPI approach to running these _in-silico_ experiments. Sadly, because of the cost of creating a reliable infrastructure, we currently cannot offer this is as a service to public but a number of institutes host bioinformatics enabled HPC environments. Some, such as http://diagcomputing.org/[DIAG], the Data Intensive Academic Grid, are freely available to any life-science researcher. We are interested in being to deploy this on an Amazon cloud (I guess that a single analysis would be about $300) but we do not currently have the manpower to accomplish that.

== What uses cases does JAMp accomodate? == 
Basically, _Just_Annotate_My_proteins_ does exactly what it reads on the tin! You give it a protein FASTA file and it annotates it with functional terms. The terms are derived from the http://www.ncbi.nlm.nih.gov/pubmed‎[literature] and the http://en.wikipedia.org/wiki/Biocurator[biocuration] teams working on linking known proteins with these terms. The use cases therefore are not restricted but we routinely use it for annotating:

* Transcriptome experiments that produce a reference sequence (an assembly)


== Authors & license ==

Copyright 2012-2014 the http://csiro.au[Commonwealth Scientific and Industrial Research Organization].

 Temi Varghese and Alexie Papanicolaou

 CSIRO Ecosystem Sciences
 temi.varghese@csiro.au
 alexie.papanicolaou@csiro.au

 This software is released under the Mozilla Public License v.2. You can find the terms and conditions at http://www.mozilla.org/MPL/2.0.
 It is provided "as is" without warranty of any kind.



